name: Build Wheel

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Package Name"
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup qemu
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Run Scripts
        run: |
          chmod -R 777 ${{ github.workspace }}
          script_name="build_${{ inputs.package }}.sh"
          sudo docker run --rm -t --security-opt seccomp:unconfined -v ${{ github.workspace }}:/data/data/com.termux/files/home termux/termux-docker:aarch64 bash ./scripts/"$script_name"
          git config core.filemode false

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add ${{ inputs.package }}
